# Generated by Django 5.2 on 2025-04-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='if_conf',
            field=models.BooleanField(default=False),
        ),
    ]
