# Generated by Django 5.2 on 2025-04-23 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_otp_if_conf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='if_conf',
            new_name='is_conf',
        ),
    ]
